### ISSUE TITLE
Duplication of string constants for the -f or --flags argument

### ISSUE THREAD

**Issue by edwinksl** [Videonauth/passgen#1]
If I run `./passgen.py -f dd`, then the string constant `digits` gets added to the `charset` variable twice, which is not what is intended. I think the string passed to the `-f` (or `--flags`) argument either should be deduplicated or the program can raise an exception to tell users to not specify duplicate characters.

**Comment by Videonauth** [comment]
Yes you're right. just have to ponder over it how I will implement it. As of now I have two possible options for doing this.
