### ISSUE TITLE
Add test for password strength

### ISSUE THREAD

**Issue by Videonauth** [Videonauth/passgen#15]
Adding a test for password strength to passgen.py to give an option to output password strength

**Comment by Videonauth** [comment]
![selection_109](https://cloud.githubusercontent.com/assets/9640109/16627707/c0084428-43ae-11e6-8630-47e1a1565342.png)

Thought about it a bit and think about using some kind of chained tests to evaluate the password giving points for each tests like shown in the picture.

**Comment by edwinksl** [comment]
Translation is needed at some point. :)

**Comment by Videonauth** [comment]
Translation: (from example where I checked the password 'test')
Evaluation criteria:
Optimal password length | per missing character| -5 | total -30
missing lower case | a-z | -20 | OK
missing upper case | A-Z | -20 | OK
missing punctuation | ;:_,.- etc.| -20 | OK
missing digits | 0-9 | -20 | OK
space or special characters | | -20 | OK
character sequence? | from the 3rd character | -20 | OK
character keyboard sequence? | from the 3rd character | -20 | OK
abc and digit sequences? | from the 3rd character | -20 | OK
password can be found with wordlist? | german&english | -20 | OK

Quality in points | >= 80 | not passed

**Comment by Videonauth** [comment]
As far i can overview it right now we need to, split the task of coding that into smaller bits. Actualy drafting it.

**Comment by Videonauth** [comment]
Basic implementation done.
